// 12 New packages to expand catalogue to 20 total
// This file is imported by seed-packages.ts

export const NEW_PACKAGES = [
    {
        title: 'Deep Dive Into The Wild',
        slug: 'deep-dive-into-the-wild',
        duration: '17 Days / 16 Nights',
        priceMin: 450000,
        priceMax: 780000,
        summary: 'The ultimate safari-focused Sri Lanka — multiple parks, best timings, slow pace.',
        fullDescription: 'A 17-day deep wildlife immersion across Sri Lanka\'s best national parks. Private jeep upgrades, leopard and elephant hotspot routing, and luxury lodge stays create an elite safari circuit that rivals East Africa — at a fraction of the distance.',
        tags: ['Wildlife', 'Luxury', 'Adventure'],
        highlights: [
            'Private jeep upgrades at every park',
            'Leopard + elephant hotspot routing',
            'Multiple national park circuit',
            'Luxury safari lodge stays',
            'Dawn & dusk game drives',
            'Wildlife photography guidance',
        ],
        inclusions: [
            'Private air-conditioned vehicle + driver',
            'Luxury safari lodges throughout',
            'Daily breakfast',
            'All national park entrance fees',
            'Private jeep safari drives',
            'Naturalist guide on safari days',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Lunch & dinner (unless stated)',
            'Camera permit fees',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Colombo', description: 'Airport welcome, transfer to Colombo. Evening at leisure.', activity: 'Colombo Welcome' },
            { day: 2, title: 'Colombo to Wilpattu', description: 'Drive northwest to Wilpattu National Park. Afternoon lodge check-in.', activity: 'Wilpattu Transfer' },
            { day: 3, title: 'Wilpattu Full Day Safari', description: 'Dawn and dusk game drives at Wilpattu — leopards, sloth bears, bird life.', activity: 'Wilpattu Safari' },
            { day: 4, title: 'Wilpattu Morning & Transfer', description: 'Early morning drive. Afternoon transfer to Anuradhapura region.', activity: 'Morning Safari' },
            { day: 5, title: 'Anuradhapura Heritage', description: 'Sacred city visit. Transfer to Minneriya/Kaudulla region.', activity: 'Ancient City' },
            { day: 6, title: 'Minneriya Elephant Gathering', description: 'Afternoon safari at Minneriya — famous elephant gathering (seasonal).', activity: 'Elephant Gathering' },
            { day: 7, title: 'Sigiriya & Village Safari', description: 'Sigiriya Rock Fortress morning. Afternoon village experience.', activity: 'Sigiriya Climb' },
            { day: 8, title: 'Kandy Transit & Evening', description: 'Scenic drive to Kandy. Temple of the Tooth evening visit.', activity: 'Kandy Evening' },
            { day: 9, title: 'Kandy to Hill Country', description: 'Morning botanical gardens. Drive into the highlands.', activity: 'Hill Country' },
            { day: 10, title: 'Horton Plains Dawn Trek', description: 'Pre-dawn start for Horton Plains World\'s End. Afternoon rest.', activity: 'Horton Plains' },
            { day: 11, title: 'Hill Country to Udawalawe', description: 'Scenic drive south. Late afternoon safari at Udawalawe.', activity: 'Udawalawe Safari' },
            { day: 12, title: 'Udawalawe Full Day', description: 'Dawn safari for elephants. Visit Elephant Transit Home. Dusk drive.', activity: 'Elephant Safari' },
            { day: 13, title: 'Udawalawe to Yala Region', description: 'Transfer to Yala. Afternoon lodge check-in. Sunset from lodge.', activity: 'Yala Region' },
            { day: 14, title: 'Yala National Park — Full Day', description: 'Dawn-to-mid-morning leopard tracking. Afternoon dusk drive.', activity: 'Leopard Safari' },
            { day: 15, title: 'Yala Morning & Coastal Transfer', description: 'Final early-morning game drive. Afternoon transfer to south coast.', activity: 'Final Safari' },
            { day: 16, title: 'Coastal Restoration', description: 'Full day at beach villa. Optional whale watching (seasonal).', activity: 'Coastal Day' },
            { day: 17, title: 'Departure', description: 'Morning at leisure, private airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/deep-dive-into-the-wild-hero.webp',
            '/images/packages/deep-dive-into-the-wild-gallery-1.webp',
            '/images/packages/deep-dive-into-the-wild-gallery-2.webp',
            '/images/packages/deep-dive-into-the-wild-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: true,
        homeRank: 2,
    },
    {
        title: 'A Quick Escape To The Hills',
        slug: 'quick-escape-to-the-hills',
        duration: '9 Days / 8 Nights',
        priceMin: 220000,
        priceMax: 380000,
        summary: 'Tea country calm with iconic rail scenery and boutique stays.',
        fullDescription: 'A focused hill country escape built around tea estate life, the iconic scenic train, and misty highland viewpoints. Ideal for couples or slow-travel seekers who want depth over distance.',
        tags: ['Hill Country', 'Nature', 'Rail'],
        highlights: [
            'Reserved scenic rail segment',
            'Tea estate bungalow stay (2 nights)',
            'Guided waterfall & viewpoint walks',
            'Tea blending workshop',
        ],
        inclusions: [
            'Private vehicle + driver throughout',
            'Boutique bungalow stays',
            'Daily breakfast',
            'Reserved rail tickets',
            'Tea tasting experience',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Meals except breakfast',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Kandy', description: 'Airport pickup, scenic drive to Kandy. Evening lakeside walk.', activity: 'Kandy Welcome' },
            { day: 2, title: 'Kandy Heritage & Crafts', description: 'Temple of the Tooth, Peradeniya Gardens, artisan workshops.', activity: 'Temple Visit' },
            { day: 3, title: 'Kandy to Tea Country', description: 'Morning drive through cascading plantations. Tea estate check-in.', activity: 'Estate Welcome' },
            { day: 4, title: 'Tea Estate Day', description: 'Factory tour, tea blending workshop, golden-hour viewpoint walk.', activity: 'Tea Blending' },
            { day: 5, title: 'Scenic Train Journey', description: 'Reserved-seat train through highland tunnels and bridges. Ella arrival.', activity: 'Scenic Rail' },
            { day: 6, title: 'Ella Viewpoints & Waterfalls', description: 'Little Adam\'s Peak sunrise hike. Ravana Falls. Nine Arches Bridge.', activity: 'Ella Exploration' },
            { day: 7, title: 'Ella to Nuwara Eliya', description: 'Highland drive to Nuwara Eliya. Afternoon town exploration.', activity: 'Hill Station' },
            { day: 8, title: 'Horton Plains Option', description: 'Optional Horton Plains dawn trek or lakeside leisure.', activity: 'Highland Leisure' },
            { day: 9, title: 'Departure', description: 'Morning at leisure, airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/quick-escape-to-the-hills-hero.webp',
            '/images/packages/quick-escape-to-the-hills-gallery-1.webp',
            '/images/packages/quick-escape-to-the-hills-gallery-2.webp',
            '/images/packages/quick-escape-to-the-hills-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'Family Escape In Paradise',
        slug: 'family-escape-in-paradise',
        duration: '19 Days / 18 Nights',
        priceMin: 480000,
        priceMax: 820000,
        summary: 'A comfort-first grand family circuit — short transfers, flexible days, beach finish.',
        fullDescription: 'The ultimate family Sri Lanka — designed with children in mind. Short transfer days, kid-friendly accommodations with pools, optional safari and marine activities, and a long beach base to finish. No rush, no stress.',
        tags: ['Family', 'Culture', 'Beach'],
        highlights: [
            'Kid-friendly boutique stays with pools',
            'Optional safari + marine day',
            'Short transfer distances',
            'Beach base finale (4 nights)',
            'Interactive village & cooking experiences',
            'Flexible rest days built in',
        ],
        inclusions: [
            'Private vehicle + driver (family-sized)',
            'Family-friendly resort stays',
            'Daily breakfast',
            'Child-friendly activity inclusions',
            'One family safari drive',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Lunch & dinner (unless stated)',
            'Optional water sports',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Negombo Rest', description: 'Airport welcome. Short transfer to beach resort. Pool time for kids.', activity: 'Family Welcome' },
            { day: 2, title: 'Negombo Discovery', description: 'Fish market morning, lagoon boat ride, afternoon pool.', activity: 'Lagoon Boat' },
            { day: 3, title: 'To Cultural Triangle', description: 'Drive north with heritage stops. Kid-friendly hotel check-in.', activity: 'Cultural Region' },
            { day: 4, title: 'Sigiriya & Village Fun', description: 'Sigiriya (or Pidurangala for younger kids). Village ox-cart & cooking.', activity: 'Village Experience' },
            { day: 5, title: 'Polonnaruwa & Safari', description: 'Morning ruins by bike. Afternoon Minneriya elephant safari.', activity: 'Elephant Safari' },
            { day: 6, title: 'To Kandy', description: 'Spice garden stop. Kandy lake walk. Evening cultural show.', activity: 'Kandy Evening' },
            { day: 7, title: 'Kandy Heritage', description: 'Botanical gardens, Temple of the Tooth, gem museum.', activity: 'Botanical Gardens' },
            { day: 8, title: 'Kandy to Hill Country', description: 'Scenic drive to tea estate. Afternoon factory tour.', activity: 'Tea Country' },
            { day: 9, title: 'Tea Country Leisure', description: 'Estate walk, viewpoint picnic, waterfall visit.', activity: 'Estate Leisure' },
            { day: 10, title: 'Scenic Train Segment', description: 'Family train experience through highlands. Kids love the bridges.', activity: 'Train Ride' },
            { day: 11, title: 'Ella Exploration', description: 'Nine Arches Bridge walk, Ravana Falls, local cafe lunch.', activity: 'Ella Discovery' },
            { day: 12, title: 'Hill Country to Udawalawe', description: 'Drive south. Late afternoon at Elephant Transit Home.', activity: 'Baby Elephants' },
            { day: 13, title: 'Udawalawe Safari', description: 'Morning game drive — elephants, peacocks, crocodiles.', activity: 'Wildlife Safari' },
            { day: 14, title: 'To Mirissa/South Coast', description: 'Transfer to beach. Afternoon beach arrival.', activity: 'Beach Arrival' },
            { day: 15, title: 'Beach Day & Turtle Hatchery', description: 'Morning turtle hatchery visit. Afternoon beach & pool.', activity: 'Turtle Experience' },
            { day: 16, title: 'Galle Fort Family Day', description: 'Galle Fort exploration, ice cream, rampart walk, shopping.', activity: 'Galle Fort' },
            { day: 17, title: 'Beach & Water Sports', description: 'Snorkeling option, beach games, sunset dinner.', activity: 'Beach Fun' },
            { day: 18, title: 'Final Beach Day', description: 'Free day — spa for parents, pool for kids. Farewell dinner.', activity: 'Farewell Day' },
            { day: 19, title: 'Departure', description: 'Leisurely breakfast, airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/family-escape-in-paradise-hero.webp',
            '/images/packages/family-escape-in-paradise-gallery-1.webp',
            '/images/packages/family-escape-in-paradise-gallery-2.webp',
            '/images/packages/family-escape-in-paradise-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: true,
        homeRank: 7,
    },
    {
        title: 'Colombo City & Coastal Weekend',
        slug: 'colombo-city-coastal-weekend',
        duration: '4 Days / 3 Nights',
        priceMin: 120000,
        priceMax: 220000,
        summary: 'Short premium break — Colombo dining + a quiet coastal reset.',
        fullDescription: 'A compact city-and-coast escape for those with limited time. Curated Colombo dining, a boutique city stay, and a coastal villa day — all within a long weekend.',
        tags: ['City', 'Beach', 'Food'],
        highlights: [
            'Curated city dining experiences',
            'Coastal villa day trip',
            'Boutique city hotel stay',
            'Local food tour option',
        ],
        inclusions: [
            'Private transfers throughout',
            'Boutique hotel stays',
            'Daily breakfast',
            'One curated dining experience',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Additional meals not listed',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Colombo Evening', description: 'Airport transfer. Boutique check-in. Curated dinner at top Colombo restaurant.', activity: 'City Dining' },
            { day: 2, title: 'Colombo Discovery', description: 'Morning heritage walk (Fort/Pettah). Afternoon spa or shopping. Rooftop sundowners.', activity: 'City Exploration' },
            { day: 3, title: 'Coastal Day', description: 'Drive to nearby coast. Beach villa day with lunch. Sunset return to Colombo.', activity: 'Coastal Escape' },
            { day: 4, title: 'Departure', description: 'Leisurely morning, airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/colombo-city-coastal-weekend-hero.webp',
            '/images/packages/colombo-city-coastal-weekend-gallery-1.webp',
            '/images/packages/colombo-city-coastal-weekend-gallery-2.webp',
            '/images/packages/colombo-city-coastal-weekend-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'Whale Coast & Galle Fort',
        slug: 'whale-coast-galle-fort',
        duration: '6 Days / 5 Nights',
        priceMin: 200000,
        priceMax: 360000,
        summary: 'Fort walls, boutique stays, and whale season routing (when conditions align).',
        fullDescription: 'A focused south-coast journey combining the charm of Galle Fort with seasonal whale watching opportunities and boutique beach stays. Built for culture lovers and marine enthusiasts.',
        tags: ['Beach', 'Culture', 'Marine'],
        highlights: [
            'Galle Fort storyteller heritage walk',
            'Whale trip option (seasonal)',
            'Boutique fort-district stay',
            'South coast beach base',
        ],
        inclusions: [
            'Private transfers throughout',
            'Boutique hotel stays',
            'Daily breakfast',
            'Galle Fort guided walk',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Whale watching trip (seasonal, priced separately)',
            'Meals except breakfast',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & South Coast', description: 'Airport transfer to south coast. Evening beach walk.', activity: 'Coastal Welcome' },
            { day: 2, title: 'Galle Fort Heritage Day', description: 'Morning heritage walk with local storyteller. Afternoon fort district shopping.', activity: 'Fort Walk' },
            { day: 3, title: 'Whale Watching Option', description: 'Early morning whale watching trip (seasonal). Afternoon beach rest.', activity: 'Marine Day' },
            { day: 4, title: 'Coastal Exploration', description: 'Stilt fishermen, sea turtle project, boutique lunch spot.', activity: 'Coast Discovery' },
            { day: 5, title: 'Beach Leisure', description: 'Full day at leisure. Spa option. Sunset dinner.', activity: 'Beach Day' },
            { day: 6, title: 'Departure', description: 'Morning at leisure, airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/whale-coast-galle-fort-hero.webp',
            '/images/packages/whale-coast-galle-fort-gallery-1.webp',
            '/images/packages/whale-coast-galle-fort-gallery-2.webp',
            '/images/packages/whale-coast-galle-fort-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'Luxury Sri Lanka In 10 Days',
        slug: 'luxury-sri-lanka-in-10-days',
        duration: '10 Days / 9 Nights',
        priceMin: 380000,
        priceMax: 680000,
        summary: 'A refined first-timer circuit: heritage + hills + coast with premium logistics.',
        fullDescription: 'The definitive luxury first-timer itinerary. Every detail is elevated — private guide days, boutique collection stays, and concierge-level timing across Sri Lanka\'s three essential regions: Cultural Triangle, Hill Country, and South Coast.',
        tags: ['Luxury', 'First-Time', 'Couples'],
        highlights: [
            'Private guide throughout',
            'Boutique stay collection (all 5-star)',
            'Scenic rail reserved seats',
            'Sunset experiences curated daily',
            'Premium dining recommendations',
        ],
        inclusions: [
            'Private luxury vehicle + driver',
            '5-star boutique stays throughout',
            'Daily breakfast',
            'Private guide (all days)',
            'All entrance fees',
            'Reserved rail tickets',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Lunch & dinner (unless stated)',
            'Spa treatments',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Colombo', description: 'VIP airport welcome. Transfer to luxury Colombo hotel. Evening Galle Face promenade.', activity: 'Colombo Welcome' },
            { day: 2, title: 'To Cultural Triangle', description: 'Drive north. Dambulla Cave Temple stop. Luxury lodge check-in.', activity: 'Heritage Region' },
            { day: 3, title: 'Sigiriya & Village', description: 'Private guided Sigiriya sunrise climb. Afternoon village immersion.', activity: 'Sigiriya Sunrise' },
            { day: 4, title: 'Polonnaruwa & Kandy', description: 'Morning ruins walk. Afternoon transfer to Kandy lakeside hotel.', activity: 'Ancient Ruins' },
            { day: 5, title: 'Kandy Culture', description: 'Temple of the Tooth, Peradeniya Gardens, cultural show. Spa evening.', activity: 'Temple Heritage' },
            { day: 6, title: 'Tea Country', description: 'Scenic drive to highlands. Tea estate check-in and tasting.', activity: 'Tea Experience' },
            { day: 7, title: 'Scenic Rail & Viewpoints', description: 'Reserved-seat scenic train. Highland viewpoint walk.', activity: 'Scenic Train' },
            { day: 8, title: 'To South Coast', description: 'Drive to coast. Galle Fort sunset walk with storyteller.', activity: 'Galle Fort Sunset' },
            { day: 9, title: 'Coastal Villa Day', description: 'Beachfront villa day. Optional whale watching. Sunset dinner.', activity: 'Villa Restoration' },
            { day: 10, title: 'Departure', description: 'Leisurely morning, VIP airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/luxury-sri-lanka-in-10-days-hero.webp',
            '/images/packages/luxury-sri-lanka-in-10-days-gallery-1.webp',
            '/images/packages/luxury-sri-lanka-in-10-days-gallery-2.webp',
            '/images/packages/luxury-sri-lanka-in-10-days-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: true,
        homeRank: 8,
    },
    {
        title: 'Tea, Trails & Waterfalls',
        slug: 'tea-trails-waterfalls',
        duration: '6 Days / 5 Nights',
        priceMin: 180000,
        priceMax: 320000,
        summary: 'Light hikes, waterfalls, and tea-country bungalows — built for calm.',
        fullDescription: 'A nature-first hill country escape focused on gentle trails, waterfall stops, and the rhythm of tea estate life. No rushed sightseeing — just highland calm.',
        tags: ['Nature', 'Slow Travel', 'Hills'],
        highlights: [
            'Viewpoint picnic experience',
            'Gentle guided trail walks',
            'Multiple waterfall stops',
            'Heritage tea bungalow stay',
        ],
        inclusions: [
            'Private vehicle + driver',
            'Tea bungalow accommodation',
            'Daily breakfast',
            'Guided nature walks',
            'Viewpoint picnic (one day)',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Meals except breakfast',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Highland Entry', description: 'Airport transfer to hill country. Tea bungalow check-in. Evening mist walk.', activity: 'Highland Welcome' },
            { day: 2, title: 'Waterfall Circuit', description: 'Morning trail to Devon Falls. Afternoon St. Clair\'s Falls viewpoint.', activity: 'Waterfall Trail' },
            { day: 3, title: 'Tea Estate Immersion', description: 'Factory tour, plucking experience, afternoon tasting. Sunset viewpoint.', activity: 'Tea Day' },
            { day: 4, title: 'Guided Nature Trail', description: 'Morning guided hike through cloud forest. Viewpoint picnic lunch.', activity: 'Nature Hike' },
            { day: 5, title: 'Lakeside & Garden Day', description: 'Gregory Lake morning. Hakgala Botanical Garden afternoon.', activity: 'Highland Leisure' },
            { day: 6, title: 'Departure', description: 'Morning at leisure, airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/tea-trails-waterfalls-hero.webp',
            '/images/packages/tea-trails-waterfalls-gallery-1.webp',
            '/images/packages/tea-trails-waterfalls-gallery-2.webp',
            '/images/packages/tea-trails-waterfalls-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'East Coast Marine Days',
        slug: 'east-coast-marine-days',
        duration: '5 Days / 4 Nights',
        priceMin: 150000,
        priceMax: 280000,
        summary: 'Turquoise east-coast days with snorkeling and lagoon sunsets.',
        fullDescription: 'The east coast is Sri Lanka\'s best-kept summer secret — crystal-clear waters, Pigeon Island snorkeling, and untouched beaches. This short break keeps it simple: long beach base, minimal transfers.',
        tags: ['Marine', 'Beach', 'Summer'],
        highlights: [
            'Pigeon Island snorkeling option',
            'Long beach base (3 nights)',
            'Lagoon sunset kayak',
            'Fresh seafood dining',
        ],
        inclusions: [
            'Private transfers',
            'Beach resort stays',
            'Daily breakfast',
            'One snorkeling excursion',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Additional water sports',
            'Meals except breakfast',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Trincomalee', description: 'Transfer to east coast. Beach resort check-in. Evening beach walk.', activity: 'Beach Welcome' },
            { day: 2, title: 'Pigeon Island Snorkeling', description: 'Morning boat to Pigeon Island. Snorkeling in crystal waters. Afternoon beach.', activity: 'Snorkeling' },
            { day: 3, title: 'Lagoon & Local Culture', description: 'Morning lagoon kayak. Afternoon local market visit. Seafood dinner.', activity: 'Lagoon Day' },
            { day: 4, title: 'Beach Leisure', description: 'Full day at the beach. Optional diving or fishing. Sunset farewell.', activity: 'Beach Day' },
            { day: 5, title: 'Departure', description: 'Morning at leisure, airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/east-coast-marine-days-hero.webp',
            '/images/packages/east-coast-marine-days-gallery-1.webp',
            '/images/packages/east-coast-marine-days-gallery-2.webp',
            '/images/packages/east-coast-marine-days-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'The Cultural Triangle Express',
        slug: 'cultural-triangle-express',
        duration: '5 Days / 4 Nights',
        priceMin: 160000,
        priceMax: 290000,
        summary: 'Sigiriya + Polonnaruwa + Kandy in a tight but premium pace.',
        fullDescription: 'A focused heritage circuit for travelers with limited time. Sigiriya\'s drama, Polonnaruwa\'s ancient ruins, and Kandy\'s sacred heritage — delivered with private guides and boutique stays in just 5 days.',
        tags: ['Heritage', 'UNESCO', 'Short Break'],
        highlights: [
            'Sigiriya sunrise option',
            'Private ruins guide at Polonnaruwa',
            'Kandy Temple evening ceremony',
            'Boutique heritage stays',
        ],
        inclusions: [
            'Private vehicle + driver',
            'Boutique hotel stays',
            'Daily breakfast',
            'Private guide (all days)',
            'All entrance fees',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Meals except breakfast',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Cultural Triangle', description: 'Airport transfer to heritage region. Dambulla Cave Temple stop. Boutique check-in.', activity: 'Heritage Welcome' },
            { day: 2, title: 'Sigiriya & Village', description: 'Sunrise Sigiriya climb with private guide. Afternoon village immersion.', activity: 'Sigiriya Sunrise' },
            { day: 3, title: 'Polonnaruwa & Minneriya', description: 'Morning ruins walk. Afternoon optional elephant safari at Minneriya.', activity: 'Ancient Ruins' },
            { day: 4, title: 'Kandy Heritage', description: 'Drive to Kandy. Temple of the Tooth. Cultural show. Lakeside evening.', activity: 'Kandy Culture' },
            { day: 5, title: 'Departure', description: 'Morning botanical gardens visit. Airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/cultural-triangle-express-hero.webp',
            '/images/packages/cultural-triangle-express-gallery-1.webp',
            '/images/packages/cultural-triangle-express-gallery-2.webp',
            '/images/packages/cultural-triangle-express-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'The Wellness Reset',
        slug: 'wellness-reset-ayurveda-lite',
        duration: '4 Days / 3 Nights',
        priceMin: 130000,
        priceMax: 240000,
        summary: 'A short reset with consultation-led treatments and quiet coastal time.',
        fullDescription: 'A compact wellness escape for those who want a taste of Ayurveda without a full retreat commitment. Initial consultation, daily treatments, and coastal calm — all in a long weekend.',
        tags: ['Wellness', 'Ayurveda', 'Slow Travel'],
        highlights: [
            'Initial Ayurveda consultation',
            'Daily wellness treatments',
            'Coastal quiet time',
            'Closing wellness recommendations',
        ],
        inclusions: [
            'Private transfers',
            'Wellness resort stay',
            'Daily breakfast',
            'Ayurveda consultation',
            'Daily treatments (2 per day)',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Additional spa services',
            'Meals except breakfast',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Consultation', description: 'Transfer to wellness retreat. Ayurveda consultation. Personalized plan created.', activity: 'Wellness Intake' },
            { day: 2, title: 'Treatment Day', description: 'Morning treatment session. Light yoga. Afternoon treatment. Coastal walk.', activity: 'Treatments' },
            { day: 3, title: 'Deep Rest & Closing', description: 'Final treatments. Closing consultation with take-home recommendations.', activity: 'Closing Session' },
            { day: 4, title: 'Departure', description: 'Mindful morning, airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/wellness-reset-ayurveda-lite-hero.webp',
            '/images/packages/wellness-reset-ayurveda-lite-gallery-1.webp',
            '/images/packages/wellness-reset-ayurveda-lite-gallery-2.webp',
            '/images/packages/wellness-reset-ayurveda-lite-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: "The Photographer's Golden Hours",
        slug: 'photographers-golden-hours',
        duration: '9 Days / 8 Nights',
        priceMin: 280000,
        priceMax: 490000,
        summary: 'Built around light: sunrise heritage, golden safari, blue-hour coast.',
        fullDescription: 'A photography-first itinerary designed around the best light. Every stop is timed for golden or blue hour. Minimal midday driving, maximum sunrise and sunset positioning. Built for serious photographers and visual storytellers.',
        tags: ['Photography', 'Wildlife', 'Nature'],
        highlights: [
            'Best-time routing for golden/blue hour',
            'Minimal midday driving',
            'Sunrise heritage + sunset safari',
            'Photography-optimized lodge positions',
            'Wildlife photography guidance',
        ],
        inclusions: [
            'Private vehicle + driver',
            'Photography-optimized lodges',
            'Daily breakfast',
            'Safari drives (timed for light)',
            'All entrance fees',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Camera equipment',
            'Park camera permits',
            'Meals except breakfast',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Blue Hour Colombo', description: 'Evening arrival. Blue-hour Colombo harbour and Galle Face shoot.', activity: 'City Blue Hour' },
            { day: 2, title: 'Sunrise at Sigiriya', description: 'Pre-dawn drive. Sigiriya Rock at first light. Golden village afternoon.', activity: 'Sigiriya Dawn' },
            { day: 3, title: 'Ancient Ruins Light', description: 'Polonnaruwa morning ruins in raking light. Minneriya golden-hour elephants.', activity: 'Heritage Light' },
            { day: 4, title: 'Kandy Morning & Tea Light', description: 'Dawn mist at Kandy Lake. Transfer to tea country for sunset glow.', activity: 'Kandy Dawn' },
            { day: 5, title: 'Train & Highland Light', description: 'Morning scenic train (window-side seat). Afternoon highland viewpoints.', activity: 'Rail Photography' },
            { day: 6, title: 'Waterfalls & Cloud Forest', description: 'Early waterfall shoots with mist. Afternoon cloud forest textures.', activity: 'Nature Textures' },
            { day: 7, title: 'Golden Safari', description: 'Dawn game drive for backlit wildlife. Dusk drive for golden dust clouds.', activity: 'Safari Light' },
            { day: 8, title: 'South Coast Blue Hour', description: 'Galle Fort golden hour. Blue-hour long exposures on coastal rocks.', activity: 'Coastal Shoot' },
            { day: 9, title: 'Departure', description: 'Sunrise beach shoot. Airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/photographers-golden-hours-hero.webp',
            '/images/packages/photographers-golden-hours-gallery-1.webp',
            '/images/packages/photographers-golden-hours-gallery-2.webp',
            '/images/packages/photographers-golden-hours-gallery-3.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'The Luxe Rail & Villa Journey',
        slug: 'luxe-rail-villa-journey',
        duration: '8 Days / 7 Nights',
        priceMin: 340000,
        priceMax: 600000,
        summary: 'Iconic hill rail + a private villa finish — simple, expensive-feeling, calm.',
        fullDescription: 'Two iconic Sri Lanka moments combined: the famous highland railway through tea country, and a private villa finale on the southern coast. Minimal stops, maximum luxury. The definition of less-is-more premium travel.',
        tags: ['Luxury', 'Rail', 'Beach'],
        highlights: [
            'Reserved scenic rail segment',
            'Private villa finish (3 nights)',
            'Highland tea experience',
            'Boutique stays throughout',
            'Villa chef dinner option',
        ],
        inclusions: [
            'Private luxury vehicle + driver',
            'Boutique + private villa stays',
            'Daily breakfast',
            'Reserved rail tickets',
            'Tea tasting experience',
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Villa chef (priced separately)',
            'Meals except breakfast',
            'Tips / personal expenses',
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Kandy', description: 'Airport transfer to Kandy boutique hotel. Evening lakeside walk.', activity: 'Kandy Welcome' },
            { day: 2, title: 'Kandy Culture', description: 'Temple of the Tooth, gardens, craft heritage. Spa afternoon.', activity: 'Heritage Day' },
            { day: 3, title: 'Tea Country Rail', description: 'Morning scenic train through tunnels and tea terraces. Estate check-in.', activity: 'Scenic Rail' },
            { day: 4, title: 'Tea Estate Day', description: 'Factory tour, tasting session, golden-hour viewpoint. Bungalow evening.', activity: 'Tea Experience' },
            { day: 5, title: 'To Private Villa', description: 'Scenic drive to south coast. Private villa check-in. Pool afternoon.', activity: 'Villa Arrival' },
            { day: 6, title: 'Villa Day — Beach & Fort', description: 'Morning beach. Afternoon Galle Fort walk. Villa sundowners.', activity: 'Coastal Day' },
            { day: 7, title: 'Villa Leisure', description: 'Full day at villa. Optional spa, optional chef dinner, or beach.', activity: 'Villa Privacy' },
            { day: 8, title: 'Departure', description: 'Leisurely morning, private airport transfer.', activity: 'Departure' },
        ],
        images: [
            '/images/packages/luxe-rail-villa-journey-hero.webp',
            '/images/packages/luxe-rail-villa-journey-gallery-1.webp',
            '/images/packages/luxe-rail-villa-journey-gallery-2.webp',
            '/images/packages/luxe-rail-villa-journey-gallery-3.webp',
        ],
        isPublished: true,
    },
    {
        title: 'Artisan in Travel, Curating Luxury',
        slug: 'artisan-in-travel-curating-luxury',
        duration: '14 Days / 13 Nights',
        priceMin: 850000,
        priceMax: 1500000,
        summary: 'Experts in tailor-made luxury travel with off-beat experiences in refined luxury.',
        fullDescription: 'Crafting bespoke journeys that highlight Sri Lanka’s culture, authenticity, and hospitality while offering discerning travelers immersive and off-beat experiences with refined luxury. Every property is 5-star or ultra-boutique, transport is in premium vehicles, and experiences are entirely private.',
        tags: ['Luxury', 'Culture', 'Experiences'],
        highlights: [
            'Private helicopter or seaplane transfers (optional)',
            'Ultra-luxury boutique hotel collection',
            'Private villa stays with personal chefs',
            'Exclusive access temple visits',
            'Sailing and private yacht experiences'
        ],
        inclusions: [
            'Premium VIP airport fast-track',
            'Luxury SUV with private chauffeur/guide',
            'All ultra-luxury accommodations',
            'Daily breakfast and curated dinners',
            'All exclusive experiences and entrance fees'
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Premium alcoholic beverages',
            'Helicopter transfers (unless requested)',
            'Tips and personal expenses'
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Colombo Elegance', description: 'VIP fast-track arrival. Transfer to historic luxury hotel. Evening private dining.', activity: 'Welcome' },
            { day: 2, title: 'Helicopter to Tea Country', description: 'Scenic flight to the central highlands. Check-in to a restored tea planter residence.', activity: 'Scenic Flight' },
            { day: 3, title: 'Private Tea Estate Immersion', description: 'Exclusive estate tour, tea tasting with the head planter, and a curated high tea.', activity: 'Tea Estate' },
            { day: 4, title: 'Descend to Yala', description: 'Drive to the deep south. Settle into a luxury tented safari lodge bordering the park.', activity: 'Safari Lodge' },
            { day: 5, title: 'Private Leopard Tracking', description: 'Full day private jeep safari with a dedicated naturalist. Sundowners in the bush.', activity: 'Wildlife Safari' },
            { day: 6, title: 'Coastal Villa Arrival', description: 'Transfer to a private beachfront villa in Tangalle or Weligama.', activity: 'Beach Villa' },
            { day: 7, title: 'Private Yacht Experience', description: 'Morning sail along the southern coast. Snorkeling, paddleboarding, and onboard chef lunch.', activity: 'Yacht Charter' },
            { day: 8, title: 'Galle Fort Heritage', description: 'Guided architectural walk through Galle Fort followed by high-end boutique shopping.', activity: 'Galle Heritage' },
            { day: 9, title: 'Villa Rest Day', description: 'A day of total relaxation. In-villa spa treatments and beachside leisure.', activity: 'Relaxation' },
            { day: 10, title: 'Departure', description: 'Smooth transfer back to Colombo airport via expressway for departure.', activity: 'Departure' }
        ],
        images: [
            '/images/tours/thumb-luxury.webp',
            '/images/home/package-luxury.webp',
            '/images/home/journey-dusk.webp',
            '/images/home/journey-dawn.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'Curating Your Healing Journey',
        slug: 'curating-your-healing-journey',
        duration: '10 Days / 9 Nights',
        priceMin: 400000,
        priceMax: 700000,
        summary: 'Combining wellness and and ayurvedic therapy prioritizing health and deep relaxation.',
        fullDescription: 'A dedicated wellness path combining authentic Ayurvedic medical tourism, prioritizing health, relaxation, and personalized care. This itinerary is designed to ensure a transformative, inclusive journey focused purely on your physical and mental well-being in the heart of nature.',
        tags: ['Wellness', 'Ayurveda', 'Slow Travel'],
        highlights: [
            'In-depth consultation with Ayurvedic doctors',
            'Daily personalized treatment plans',
            'Yoga and deep meditation sessions',
            'Organic, dosha-specific meals',
            'Silent nature walks and digital detox'
        ],
        inclusions: [
            'Private comfortable transfers',
            'Specialized eco-wellness resort stays',
            'Full board (all specialized meals included)',
            'All Ayurveda treatments and consultations',
            'Daily guided yoga and meditation'
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'External excursions non-related to wellness',
            'Tips / personal expenses'
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Grounding', description: 'Transfer to a quiet sanctuary near Negombo. Gentle evening meditation.', activity: 'Arrival' },
            { day: 2, title: 'Journey to the Jungle', description: 'Drive to the central highlands wellness retreat. Initial medical consultation.', activity: 'Consultation' },
            { day: 3, title: 'Detoxification Phase', description: 'First full day of treatments. Shirodhara and herbal baths. Gentle evening yoga.', activity: 'Treatments' },
            { day: 4, title: 'Mindful Nature Immersion', description: 'Morning treatments followed by a silent, guided walk through surrounding forests.', activity: 'Nature Walk' },
            { day: 5, title: 'Deep Healing', description: 'Intensive therapeutic massages and acupuncture sessions. Nutrition class.', activity: 'Therapy' },
            { day: 6, title: 'Transition to Coast', description: 'Transfer to a quiet southern beach Ayurveda resort. Afternoon sound bath.', activity: 'Relocation' },
            { day: 7, title: 'Coastal Rejuvenation', description: 'Sunrise yoga on the beach. Special oil treatments. Sunset meditation.', activity: 'Beach Yoga' },
            { day: 8, title: 'Closing Consultations', description: 'Final evaluations with doctors. Establishing an at-home continuation plan.', activity: 'Evaluation' },
            { day: 9, title: 'Integration Day', description: 'A relaxed day to integrate the healing. Light massages, pool time, reading.', activity: 'Integration' },
            { day: 10, title: 'Departure', description: 'Refreshed and renewed, private transfer to the airport.', activity: 'Departure' }
        ],
        images: [
            '/images/tours/thumb-wellness.webp',
            '/images/home/package-wellness.webp',
            '/images/home/journey-afternoon.webp',
            '/images/home/journey-dawn.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    },
    {
        title: 'Escape the Ordinary',
        slug: 'escape-the-ordinary',
        duration: '12 Days / 11 Nights',
        priceMin: 320000,
        priceMax: 650000,
        summary: 'Experience the world, one journey at a time. Where adventure awaits at every turn.',
        fullDescription: 'Discover paths only a few dare to take. This high-octane itinerary combines Sri Lanka\'s most thrilling landscapes—from climbing forgotten peaks and white-water rafting, to off-road safaris and surfing wild breaks. For those who seek adrenaline packaged perfectly.',
        tags: ['Adventure', 'Nature', 'Experiences'],
        highlights: [
            'White water rafting in Kitulgala',
            'Summit challenging non-tourist peaks',
            'Remote off-road jeep safaris',
            'Surfing and deep sea fishing',
            'River canyoning and waterfall abseiling'
        ],
        inclusions: [
            '4x4 rugged comfortable vehicle + driver',
            'Eco-lodges and premium glamping stays',
            'Daily breakfast and packed trail lunches',
            'All technical equipment for sports',
            'Expert local adventure guides'
        ],
        exclusions: [
            'International flights',
            'Visa fees',
            'Dinners',
            'Extreme sports insurance (required)',
            'Tips / personal expenses'
        ],
        itinerary: [
            { day: 1, title: 'Arrival & Briefing', description: 'Airport pickup. Transfer to Kitulgala eco-lodge. Evening gear check and safety briefing.', activity: 'Arrival' },
            { day: 2, title: 'Kitulgala Rapids', description: 'Morning white-water rafting on the Kelani River. Afternoon waterfall abseiling.', activity: 'Rafting' },
            { day: 3, title: 'Trek to Adams Peak', description: 'Drive to Hatton area. Midnight ascent of Adam\'s Peak to catch the legendary sunrise.', activity: 'Mountain Trek' },
            { day: 4, title: 'Highland Recovery', description: 'Descend the mountain. Transfer to Ella. Afternoon rest and local cafe exploration.', activity: 'Recovery' },
            { day: 5, title: 'Ella Rock & Zipline', description: 'Hike to the summit of Ella Rock. Afternoon adrenaline rush at the Flying Ravana mega zipline.', activity: 'Hiking' },
            { day: 6, title: 'Off-Road Safari', description: 'Drive to the east. Afternoon rugged off-road jeep safari through Gal Oya national park boundaries.', activity: '4x4 Safari' },
            { day: 7, title: 'Arugam Bay Surf', description: 'Head to the surf coast. Morning surf lesson or session for experienced riders.', activity: 'Surfing' },
            { day: 8, title: 'Deep Sea Exploration', description: 'Early morning deep-sea fishing or advanced dive trip to historical wrecks.', activity: 'Marine Adventure' },
            { day: 9, title: 'Coastal Scootering', description: 'Rent scooters to explore hidden coves and untouched beaches along the southeast coastline.', activity: 'Exploration' },
            { day: 10, title: 'Kumana Safari', description: 'Full day expedition into Kumana National Park tracking leopards and rare birdlife.', activity: 'Wildlife' },
            { day: 11, title: 'Return Transit', description: 'Long scenic drive back towards the west coast. Final celebratory dinner in Colombo.', activity: 'Transit' },
            { day: 12, title: 'Departure', description: 'Transfer to airport for your onward flight.', activity: 'Departure' }
        ],
        images: [
            '/images/tours/thumb-adventure.webp',
            '/images/home/package-adventure.webp',
            '/images/home/journey-dawn.webp',
            '/images/home/journey-afternoon.webp',
        ],
        isPublished: true,
        isFeaturedHome: false,
        homeRank: 0,
    }
];
